version: '3.13'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: stock_log
      MYSQL_USER: stocklogadmin
      MYSQL_PASSWORD: aY3ztL866/tO
      MYSQL_ROOT_PASSWORD: q7C4pk71E7£4
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web:
    build:
      context: .
    container_name: django_container
    command: uvicorn stock_log.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=stock_log
      - DATABASE_USER=stocklogadmin
      - DATABASE_PASSWORD=aY3ztL866/tO
    networks:
      - mynetwork

networks:
  mynetwork:
volumes:
  db_data:
